### ISSUE TITLE
frontend: new user profile fields are uninitialized

### ISSUE THREAD

**Issue by notsoli** [Music-Visualization-MQP/mono-repo#30]
Registration does not add a new row to the 'Profiles" table. As a result, when a new user accesses their profile page, all fields display as 'undefined'.

<img width="420" alt="Screenshot 2024-10-21 at 9 37 14 PM" src="https://github.com/user-attachments/assets/b941ff4c-eea9-4239-a28d-b2d617ab4ff9">

**Comment by michibatoryu** [comment]
Either make a new profile when a new user is registered or when a user goes to their profile, check if they have an existing profile, if not create and send if so send
